name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
#  unit_tests:
#    runs-on: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Unit tests
#        run: ./gradlew test
#  android_tests:
#    runs-on: [ macos-latest ]
#    steps:
#      - uses: actions/checkout@v2
#
#      - name: Instrumentation Tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: 29
#          script: ./gradlew connectedAndroidTest
  build:
#    needs: [ gradle, unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Release AAB
        run: ./gradlew bundleRelease
      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: Save APPBUNDLE to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: APPBUNDLE
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
      - name: Save MAPPING to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MAPPING
          path: app/build/outputs/mapping/release/mapping.txt
  deploy-play-store:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get APPBUNDLE from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: APPBUNDLE
      - name: Get MAPPING from Artifacts
        uses: actions/download-artifact@v2
        with:
          name: MAPPING
      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.meliksahcakir.spotialarm
          releaseFiles: app-release.aab
          track: internal
#          userFraction: 1.0
          mappingFile: mapping.txt
          whatsNewDirectory: whatsnew